### ISSUE TITLE
Add and configure MediatR

### ISSUE THREAD

**Issue by pobiega** [Code2Gether-Discord/Congo#20]
It was decided by votes on the discord that we use the CQRS pattern using the MediatR library.

This task is to add MediatR and set it up for use in the api project.

**Comment by Palisar** [comment]
Would this be a lot easier to implement once we have our DB and models in place?

**Comment by chrisK00** [comment]
> Would this be a lot easier to implement once we have our DB and models in place?

This is only setting it up so it's ready to be used and MediatR has no relation to our DB in any way.
The workflow will be like
`Controller -> MediatR -> DB` 
more detailed
`Controller sends a Request (Command-Write operation or Query-Read operation) to MediatR  -> MediatR maps the request to the correct Handler -> The handler has the opportunity of using the Data Context`

This makes it super easy to test our app logic and debug because most of it will be inside the handlers, keeping our controllers clean. It also helps with maintainability because the handler is either returning something or it is not. This also helps us achieve the SRP in SOLID. There's plenty of benefits.

**Comment by Palisar** [comment]
I have added and configured up Mediatr, i will need some help with getting it connected into that Database, but for now i have it setup and working with some examples using a mock Database and Data Access. I didnt want to submit this for review yet as i dont think this should be pushed to the dev branch as there is a lot of things here we will remove and change but for now, its building and working with my demo classes

https://github.com/Code2Gether-Discord/Congo/tree/feature/20-Add-Mediatr-DEMO
