### ISSUE TITLE
Codify C# coding conventions

### ISSUE THREAD

**Issue by ThorstenSauter** [Code2Gether-Discord/Congo#28]
In order to make code more readable and consistent, a root `.editorconfig` file should be created. In the meeting on 2021-10-02 it was decided to mostly follow Microsoft coding conventions. I took this to mean we should follow the guidelines set out in [this article](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) which references the dotnet runtime project as its basis. Their [.editorconfig](https://github.com/dotnet/runtime/blob/main/.editorconfig) would therefore be a good starting point.

If our individual subprojects want to define further rules, they can do so with a nested `.editorconfig` file.

Questions that should be answered:
- What is our preference regarding `var`?
- What is our preference regarding expression bodied members?
- Should `// TODO` comments be allowed in merged PRs and if not, can we enforce this?

If any other questions arise, feel free to ask them here and we can discuss them.

@pobiega  I'm still not clear on the labels or projects to assign to these all-encompassing issues, would you be so kind as to assign the appropriate ones?

**Comment by pobiega** [comment]
1. I personally prefer `var`, but I know not everyone else does. I suggest we allow both and suggest neither.
2. I like them but don't feel strongly enough to turn on suggestions. I suggest allow but not suggest.
3. Allow TODOs. Otherwise, someone might just remove the comment and then we are worse of.

No further questions from me at this point, the suggested editorconfig looks good!
